### ISSUE TITLE
No Sql

### ISSUE THREAD

**Issue by Joeso** [adameverson/tibia-web#1]
Hi, please add the SQL base skeleton

**Comment by adameverson** [comment]
![image](https://user-images.githubusercontent.com/24993219/143771480-b15b9d0b-fac4-470f-81fc-af35dd36b9fd.png)

**Comment by adameverson** [comment]
CREATE TABLE `ottibia` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `username` varchar(20) NOT NULL,
 `password` varchar(20) NOT NULL,
 `x` int(11) NOT NULL,
 `y` int(11) NOT NULL,
 `direcao` int(11) NOT NULL,
 `nivel` int(11) NOT NULL,
 `hp` int(11) NOT NULL,
 `outfit` varchar(20) NOT NULL,
 `mensagem` varchar(100) NOT NULL,
 `json` varchar(100) NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=40 DEFAULT CHARSET=latin1
