### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by Joeso** [adameverson/tibia-web#2]
Greetings, friend, congratulations on the holidays.
I study your code in my free time. Please indicate your contacts in the readmi, for example, mail or discord. So we will be able to do more. 
I'm looking at the code, I want to ask about the map. is it possible to upload an image as a background? I tried to specify a picture in mapa1, but it moves along with the character. 
<div id='mapa1'style=' background: url(1.png); position:fixed; top: -60; left: -60;'>
and I also made the tile transparent. 
thanks

**Comment by adameverson** [comment]
Joeso thank you my friend. You can keep creating new Issues it's good for the project and for github, with time we can understand each other better and do great things. By background do you mean the "painel" parts?
![image](https://user-images.githubusercontent.com/24993219/148458522-1a455200-fae3-4a59-b520-ce0a0c867b38.png)

**Comment by adameverson** [comment]
Because this other indication is composed of parts:
![image](https://user-images.githubusercontent.com/24993219/148460764-2cd79faa-e265-4005-9a4d-311dddde823b.png)

**Comment by adameverson** [comment]
The map is assembled by the map matrix:
![image](https://user-images.githubusercontent.com/24993219/148461946-eb3995a8-531c-46ad-af93-3b85ba055ca4.png)

**Comment by adameverson** [comment]
Unfortunately I still don't use a program to edit the matrix.
You can split your image into parts and compose a new map matrix with new images.
The idea is that dividing the image into parts it is possible to compose a limitless map.
Each number in the matrix identifies an image.

**Comment by Joeso** [comment]
Thank you, I understand that each part will receive a picture from the matrix of the card according to the number. To make such a matrix is a huge effort. OK, I will continue the work as I want to redo the matrix after all by loading the background. I'm just planning to upload minimaps schematically to the file where 1 is a pass 0 block and have a background. In any case, I will inform you about the work done!

**Comment by adameverson** [comment]
It seems to be more practical what you are trying to do. If you need more information I am available.

**Comment by Joeso** [comment]
I conducted some experiments in my spare time. I have a number of serious problems I can't figure out how to calculate coordinates, I tried using your technology for mapa1, but it doesn't fit.
I added the following to line 41 `<div id='mapa1' style='background: url(https://i.pinimg.com/originals/6c/6c/3a/6c6c3a21885e43a46a7a40ef37300a10.png); position:fixed; top: -60; left: -60;'>`
Made imagemCampo.png transparent.
I also added to  line 3774
 `           
cima = function (){
var quadrosDeAnimacaoInterno = quadrosDeAnimacao;
                var esperaPorQuadroInterno = esperaPorQuadro;
                while(quadrosDeAnimacaoInterno > 0){
                    setTimeout(function(){ document.getElementById('mapa1').style.top = (parseInt(document.getElementById('mapa1').style.top.split('p')[0]) + (mover/quadrosDeAnimacao)); }, esperaPorQuadroInterno);
setTimeout(function(){ document.getElementById('mapa1').style.backgroundPosition = "center -" + ultim_x * 60 + "px"; });   
					quadrosDeAnimacaoInterno--;
                    esperaPorQuadroInterno = esperaPorQuadroInterno + esperaPorQuadro;
                }
                setTimeout(function(){ document.getElementById('mapa1').style.visibility = "hidden"; document.getElementById('mapa1').style.top = -60; preencherImagens(); document.getElementById('mapa1').style.visibility = "visible"; }, esperaPorQuadroInterno);
 		   }
            direita = function (){
                var quadrosDeAnimacaoInterno = quadrosDeAnimacao;
                var esperaPorQuadroInterno = esperaPorQuadro;
                while(quadrosDeAnimacaoInterno > 0){
                    setTimeout(function(){ document.getElementById('mapa1').style.left = (parseInt(document.getElementById('mapa1').style.left.split('p')[0]) - (mover/quadrosDeAnimacao)); }, esperaPorQuadroInterno);
setTimeout(function(){ document.getElementById('mapa1').style.backgroundPosition = "-" + ultim_y * 60 + "px center"; });               
					quadrosDeAnimacaoInterno--;
                    esperaPorQuadroInterno = esperaPorQuadroInterno + esperaPorQuadro;
                }
                setTimeout(function(){ document.getElementById('mapa1').style.visibility = "hidden"; document.getElementById('mapa1').style.left = -60; preencherImagens(); document.getElementById('mapa1').style.visibility = "visible"; }, esperaPorQuadroInterno);
 			}
            baixo = function (){
                var quadrosDeAnimacaoInterno = quadrosDeAnimacao;
                var esperaPorQuadroInterno = esperaPorQuadro;
                while(quadrosDeAnimacaoInterno > 0){
                    setTimeout(function(){ document.getElementById('mapa1').style.top = (parseInt(document.getElementById('mapa1').style.top.split('p')[0]) - (mover/quadrosDeAnimacao)); }, esperaPorQuadroInterno);
setTimeout(function(){ document.getElementById('mapa1').style.backgroundPosition = "center -" + ultim_x * 60 + "px";});   
                    quadrosDeAnimacaoInterno--;
                    esperaPorQuadroInterno = esperaPorQuadroInterno + esperaPorQuadro;
                }
                setTimeout(function(){ document.getElementById('mapa1').style.visibility = "hidden"; document.getElementById('mapa1').style.top = -60; preencherImagens(); document.getElementById('mapa1').style.visibility = "visible"; }, esperaPorQuadroInterno);
            }
            esquerda = function (){
                var quadrosDeAnimacaoInterno = quadrosDeAnimacao;
                var esperaPorQuadroInterno = esperaPorQuadro;
                while(quadrosDeAnimacaoInterno > 0){
                    setTimeout(function(){ document.getElementById('mapa1').style.left = (parseInt(document.getElementById('mapa1').style.left.split('p')[0]) + (mover/quadrosDeAnimacao)); }, esperaPorQuadroInterno);
setTimeout(function(){ document.getElementById('mapa1').style.backgroundPosition = "-" + ultim_y * 60 + "px center"; }); 
                    quadrosDeAnimacaoInterno--;
                    esperaPorQuadroInterno = esperaPorQuadroInterno + esperaPorQuadro;
                }
                setTimeout(function(){ document.getElementById('mapa1').style.visibility = "hidden"; document.getElementById('mapa1').style.left = -60; preencherImagens(); document.getElementById('mapa1').style.visibility = "visible"; }, esperaPorQuadroInterno);      
		 }
             `
However, it turns out that they do not get up smoothly. 60 is the tile size. unfortunately, it turns out to be pulling somehow. backgroundPositionX and backgroundPositionY don't work in this case.
Perhaps you have a better option to calculate the coordinates of the map and smooth out the twitching?

**Comment by adameverson** [comment]
Try it this way:
`cima = function (){ 
    var quadrosDeAnimacaoInterno = quadrosDeAnimacao; 
    var esperaPorQuadroInterno = esperaPorQuadro; 
    while(quadrosDeAnimacaoInterno > 0){ 
        setTimeout(function(){ document.getElementById('mapa1').style.top = (parseInt(document.getElementById('mapa1').style.top.split('p')[0]) + (mover/quadrosDeAnimacao)); }, esperaPorQuadroInterno); 
        quadrosDeAnimacaoInterno--; 
        esperaPorQuadroInterno = esperaPorQuadroInterno + esperaPorQuadro; 
    } 
    setTimeout(function(){ document.getElementById('mapa1').style.visibility = "hidden"; 
document.getElementById('mapa1').style.top = -60; document.getElementById('mapa1').style.backgroundPosition = "center -" + ultim_x * 60 + "px"; preencherImagens(); document.getElementById('mapa1').style.visibility = "visible"; }, esperaPorQuadroInterno); 
}`
Can you move up your branch?

**Comment by Joeso** [comment]
You are a magician, you found your mistake, thank you very much. That's great!

**Comment by Joeso** [comment]
You are a magician, I found my mistake, thank you very much. That's great! I will continue and inform you about my news

**Comment by Joeso** [comment]
Hi, my idea fails.
I'm trying to fasten [game](http://instantsoft.ru/rpg2d/game.html) [sourse](http://instantsoft.ru/rpg2d/game.zip). Maybe you will have ideas with a map and animation and it will help.
